SP-3826 Support prebuild
Super-Protocol/uplink-nodejs-sp pull request #6
Opened 2024-02-08 09:25 UTC by DmitrySmv

2024-02-10 18:51 UTC, AgentRX requested changes

2024-02-10 18:51 UTC, AgentRX commented on .github/workflows/build.yml
> +          # - ubuntu-20.04
а почему отключены?

2024-02-12 08:07 UTC, DmitrySmv commented on .github/workflows/build.yml
> +          # - ubuntu-20.04
Потому что мне пока требуется тестировать сборку только под Windows.

2024-02-12 08:07 UTC, DmitrySmv commented on .github/workflows/build.yml
> +          # - ubuntu-20.04
PR is in progress

2024-02-13 12:48 UTC, DmitrySmv commented
Changes of this PR moved to https://github.com/Super-Protocol/uplink-nodejs-sp/pull/7.

2024-02-13 12:48 UTC, closed without merging